# Generated by Django 2.2.4 on 2019-10-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('course_code', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plo_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(max_length=1500)),
                ('batch', models.CharField(default=2015, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=4)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slo_code', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(max_length=1500)),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Plo')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Semester')),
                ('students', models.ManyToManyField(to='my_admin.Student')),
            ],
        ),
        migrations.AddField(
            model_name='plo',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Program'),
        ),
        migrations.CreateModel(
            name='Clo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(max_length=1500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Course')),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Slo')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_count', models.IntegerField()),
                ('question_no', models.IntegerField()),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=3)),
                ('assessment_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.AssessmentTool')),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Clo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
