# Generated by Django 2.2.4 on 2019-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_auto_20191015_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='clo_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plo',
            name='plo_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='slo',
            name='slo_code',
            field=models.CharField(max_length=2),
        ),
    ]
